server:
  port: 8084

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:h2:mem:bookingdb;MODE=MySQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  cloud:
    consul:
      enabled: false

security:
  api:
    enabled: false
    header: X-API-KEY
    key: dev-local-key

clients:
  seating:
    url: http://localhost:8083
  payment:
    url: http://localhost:8085

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
