ALTER TABLE bookings
    ADD COLUMN seat_total DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN convenience_fee DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN gst_amount DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN discount_amount DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN card_type VARCHAR(10);
