server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
        - RemoveRequestHeader=Set-Cookie
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false
      routes:
        - id: movies-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/movies/**
        - id: theatre-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/theatres/**,/api/shows/**
        - id: seating-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/seats/**
        - id: booking-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/bookings/**
        - id: payment-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/payments/**
    consul:
      enabled: false

security:
  api:
    enabled: false
    header: X-API-KEY
    key: dev-local-key

management:
  endpoints:
    web:
      exposure:
        include: health,info
