server:
  port: ${PORT:8080}

spring:
  application:
    name: gateway-service
  cloud:
    consul:
      enabled: true
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        register: true
        service-name: gateway-service
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - RemoveRequestHeader=Cookie
        - RemoveRequestHeader=Set-Cookie
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

security:
  api:
    enabled: true
    header: X-API-KEY
    key: ${API_KEY:cinema-dev-key}

management:
  endpoints:
    web:
      exposure:
        include: "*"
