CREATE DATABASE IF NOT EXISTS icinema_movies;
CREATE DATABASE IF NOT EXISTS icinema_theatre;
CREATE DATABASE IF NOT EXISTS icinema_seating;
CREATE DATABASE IF NOT EXISTS icinema_booking;
CREATE DATABASE IF NOT EXISTS icinema_payment;
