spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/icinema_theatre
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  cloud:
    consul:
      enabled: true
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        register: true
        service-name: theatre-service

security:
  api:
    enabled: true
    header: X-API-KEY
    key: ${API_KEY:cinema-dev-key}

server:
  port: ${PORT:8082}

clients:
  movies:
    url: http://${MOVIES_HOST:localhost}:${MOVIES_PORT:8081}
